import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import TopBar from "@/components/TopBar/TopBar";
import Footer from "@/components/Footer/Footer";
import Navbar from "@/components/Navbar/Navbar";
import React from "react";

const josefin = Josefin_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "New Abhishek Books And Stationery",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={josefin.className}>
        <React.StrictMode>
          <TopBar />
          <Navbar />
          <div className="outer">{children}</div>
          <Footer />
        </React.StrictMode>
      </body>
    </html>
  );
}
